apiRules:
- include:
    uidRegex: ^DocFxForUnity
    type: Namespace
- include:
    uidRegex: ^JLChnToZ\.VRC
    type: Namespace
- include:
    uidRegex: ^VVMW\.
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace